addons:
  postgresql: "9.6"
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.8
before_script:
  - cp -f src/test/resources/application.travis.conf src/test/resources/application.conf
  - cp -f src/test/resources/application.travis.conf src/main/resources/application.conf
  - psql -c 'create database whosin_test;' -U postgres
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
